config/routes.rb
RoRT::Application.routes.draw do

  resources :users
  resources :sessions, :only => [:new, :create, :destroy]
  resources :posts

  match '/signup',  :to => 'users#new'
  match '/all',  :to => 'users#index'
  match '/mail',  :to => 'posts#show'
  match '/signin',  :to => 'sessions#new'
  match '/signout', :to => 'sessions#destroy'

  root :to => "users#edit"

end

app/models/post.rb
class Post < ActiveRecord::Base
    attr_accessible :content, :user_from, :user_to

end

app/models/user.rb
class User < ActiveRecord::Base

  attr_accessor :password
  attr_accessible :name, :password, :password_confirmation

  validates :name, :presence => true
  validates :password, :confirmation => true




  def has_password?(submitted_password)
    encrypted_password == encrypt(submitted_password)
  end

  def self.authenticate(name, submitted_password)
    user = find_by_name(name)
    return nil  if user.nil?
    return user if user.has_password?(submitted_password)
  end

  def self.authenticate_with_salt(id, cookie_salt)
    user = find_by_id(id)
    (user && user.salt == cookie_salt) ? user : nil
  end

 before_save :encrypt_password


  private

    def encrypt_password
      self.salt = make_salt if new_record?
      self.encrypted_password = encrypt(password)
    end

    def encrypt(string)
      secure_hash("#{salt}--#{string}")
    end

    def make_salt
      secure_hash("#{Time.now.utc}--#{password}")
    end

    def secure_hash(string)
      Digest::SHA2.hexdigest(string)
    end


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  include SessionsHelper
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  def create
     @pos = Post.create(params[:post])
    if @pos.save
      redirect_to(:back)
    end
  end
  def show
     @post = Post.all.reverse
     @user = User.all
    render 'mail/mail'
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end



  def create
    user = User.authenticate(params[:session][:name],
                             params[:session][:password])
    if user.nil?
      flash.now[:error] = "Invalid email/password combination."
      render 'new'
    else
      sign_in user
      redirect_to users_path

    end
  end

  def destroy
    sign_out
    redirect_to root_path
  end




end

app/controllers/users_controller.rb
class UsersController < ApplicationController


  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
    @pos = Post.new
    @post = Post.all.reverse

  end


  def new
    @user = User.new
  end

  def create
    @user = User.new(params[:user])
    if @user.save
      sign_in @user
      redirect_to(@user,:notice => 'User was successfully created.')
    else
      @title = "Sign up"
      render 'new'
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper

end

app/helpers/sessions_helper.rb
module SessionsHelper
  def sign_in(user)
    cookies.permanent.signed[:remember_token] = [user.id, user.salt]
    self.current_user = user
  end

  def current_user=(user)
    @current_user = user
  end

  def signed_in?
    !current_user.nil?
  end



  def sign_out
    cookies.delete(:remember_token)
    self.current_user = nil
  end

  def current_user
    @current_user ||= user_from_remember_token
  end


   private

    def user_from_remember_token
      User.authenticate_with_salt(*remember_token)
    end

    def remember_token
      cookies.signed[:remember_token] || [nil]
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RoRT</title>
  <%= stylesheet_link_tag :all %>
  <%= javascript_include_tag :defaults %>
  <%= csrf_meta_tag %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/shared/_new.html.erb
<%= form_for @pos do |f| %>

 <%= f.text_area :content, :rows=>5 %>
 <%= f.text_field :user_to, :type=>"hidden", :value=>@user.id  %>
 <%= f.text_field :user_from, :type=>"hidden", :value=>current_user.id  %>
 <%= f.submit "Post" %>


 <% end -%>

app/views/users/_form.html.erb
<h1>Sign up</h1>
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :password %><br />
    <%= f.text_field :password %>
  </div>
   <div class="field">
    <%= f.label :password_confirmation, "Confirmation" %><br />
    <%= f.password_field :password_confirmation %>
  </div>
  <div class="actions">
    <%= f.submit "Sign up" %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Hello!</h1>
<%= link_to "Sign in", signin_path %>
<%= link_to "Sign up", signup_path %>

app/views/users/index.html.erb
<h1>Welcome <%= current_user.name %>!</h1>

   <%= link_to "Sign out", signout_path, :method => :delete %>
   <%= link_to "Mail", mail_path %>
<table>
  <tr>
    <th>Name</th>
  </tr>



<% @users.each do |user| %>
  <tr>
    <td><%= link_to user.name, user %></td>

   </tr>
<% end %>
</table>

<br />

app/views/users/new.html.erb
<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<h1>
  <b>Name:</b>
 <%= link_to @user.name, @user %>

</h1>

<%= link_to 'Back', users_path %>

 <%= render 'shared/new' %>

<% @post.each do |post| -%>
<% if (post.user_from==current_user.id && post.user_to==@user.id)%>
 <%= current_user.name %> to <%= @user.name %>


<br/>
<%= post.content %><br />
<%= post.created_at %><hr />
<%end%>

<% if (post.user_from==@user.id && post.user_to==current_user.id)%>
 <%= @user.name %> to <%= current_user.name %>
    <br/>
    <%= post.content %><br />
<%= post.created_at %>


 <hr /><% end %>
 <% end %>



<%= link_to 'Back', users_path %>